<a href="https://colab.research.google.com/github/Marteldelfer/PISI3/blob/analise-exploratoria/tmdb_profit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
tmdb_df = pd.read_csv('tmdb_completo.csv')
tmdb_df.head()

,id,title,vote_average,vote_count,release_date,revenue,runtime,budget,original_language,popularity,...,production_companies,production_countries,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes
0,5,Four Rooms,5.861,2687.0,1995-12-09,4257354.0,98.0,4000000.0,en,9.6284,...,"Miramax, A Band Apart",United States of America,"Quinn Hellerman, Lawrence Bender, Tim Roth, La...","Allison Anders, Robert Rodriguez, Alexandre Ro...","Phil Parmet, Rodrigo García, Guillermo Navarro...","Allison Anders, Robert Rodriguez, Alexandre Ro...","Lawrence Bender, Alexandre Rockwell, Quentin T...",Combustible Edison,6.7,114082.0
1,6,Judgment Night,6.500,349.0,1993-10-15,12136938.0,109.0,21000000.0,en,4.5607,...,"Largo Entertainment, JVC, Universal Pictures",United States of America,"Michael Scranton, Hank McGill, Donovan D. Ross...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Lloyd Segan, Marilyn Vance",Alan Silvestri,6.6,19885.0
2,11,Star Wars,8.204,21103.0,1977-05-25,775398007.0,121.0,11000000.0,en,67.2931,...,"Lucasfilm Ltd., 20th Century Fox",United States of America,"Paul Blake, Hal Wamsley, David Prowse, Larry W...",George Lucas,Gilbert Taylor,George Lucas,"Gary Kurtz, George Lucas, Rick McCallum",John Williams,8.6,1504993.0
3,12,Finding Nemo,7.815,19616.0,2003-05-30,940335536.0,100.0,94000000.0,en,18.2106,...,Pixar,United States of America,"Jeff Pidgeon, Danny Mann, Jessie Flower, Bill ...",Andrew Stanton,"Sharon Calahan, Jeremy Lasky","Bob Peterson, Will Csaklos, Ronnie del Carmen,...","John Lasseter, Graham Walters",Thomas Newman,8.2,1158248.0
4,13,Forrest Gump,8.468,28113.0,1994-06-23,677387716.0,142.0,55000000.0,en,27.4853,...,"Paramount Pictures, The Steve Tisch Company, W...",United States of America,"Margo Moorer, Joe Stefanelli, Ed Davis, Elizab...",Robert Zemeckis,Don Burgess,"Winston Groom, Eric Roth","Wendy Finerman, Steve Tisch, Steve Starkey",Alan Silvestri,8.8,2374308.0

In [ ]:
tmdb_df = tmdb_df[tmdb_df['budget'] != 0]
tmdb_df

,id,title,vote_average,vote_count,release_date,revenue,runtime,budget,original_language,popularity,...,production_companies,production_countries,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes
0,5,Four Rooms,5.861,2687.0,1995-12-09,4257354.0,98.0,4000000.0,en,9.6284,...,"Miramax, A Band Apart",United States of America,"Quinn Hellerman, Lawrence Bender, Tim Roth, La...","Allison Anders, Robert Rodriguez, Alexandre Ro...","Phil Parmet, Rodrigo García, Guillermo Navarro...","Allison Anders, Robert Rodriguez, Alexandre Ro...","Lawrence Bender, Alexandre Rockwell, Quentin T...",Combustible Edison,6.7,114082.0
1,6,Judgment Night,6.500,349.0,1993-10-15,12136938.0,109.0,21000000.0,en,4.5607,...,"Largo Entertainment, JVC, Universal Pictures",United States of America,"Michael Scranton, Hank McGill, Donovan D. Ross...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Lloyd Segan, Marilyn Vance",Alan Silvestri,6.6,19885.0
2,11,Star Wars,8.204,21103.0,1977-05-25,775398007.0,121.0,11000000.0,en,67.2931,...,"Lucasfilm Ltd., 20th Century Fox",United States of America,"Paul Blake, Hal Wamsley, David Prowse, Larry W...",George Lucas,Gilbert Taylor,George Lucas,"Gary Kurtz, George Lucas, Rick McCallum",John Williams,8.6,1504993.0
3,12,Finding Nemo,7.815,19616.0,2003-05-30,940335536.0,100.0,94000000.0,en,18.2106,...,Pixar,United States of America,"Jeff Pidgeon, Danny Mann, Jessie Flower, Bill ...",Andrew Stanton,"Sharon Calahan, Jeremy Lasky","Bob Peterson, Will Csaklos, Ronnie del Carmen,...","John Lasseter, Graham Walters",Thomas Newman,8.2,1158248.0
4,13,Forrest Gump,8.468,28113.0,1994-06-23,677387716.0,142.0,55000000.0,en,27.4853,...,"Paramount Pictures, The Steve Tisch Company, W...",United States of America,"Margo Moorer, Joe Stefanelli, Ed Davis, Elizab...",Robert Zemeckis,Don Burgess,"Winston Groom, Eric Roth","Wendy Finerman, Steve Tisch, Steve Starkey",Alan Silvestri,8.8,2374308.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19989,1452426,24: Redemption,9.000,1.0,2008-11-23,13593473.0,102.0,4.0,en,0.8000,...,"Imagine Television Studios, Teakwood Lane Prod...",United States of America,"Colm Feore, Cherry Jones, Kiefer Sutherland, P...",Jon Cassar,NaN,"Robert Cochran, Joel Surnow, Howard Gordon",NaN,NaN,7.4,29411.0
19990,1457688,Love Under Construction,0.000,0.0,2025-02-28,600.0,186.0,600.0,ml,0.3335,...,Rejaputhra Visual Media,India,"Ganga Meera, Gouri G Kishan, Neeraj Madhav, Aj...",Vishnu G Raghav,NaN,NaN,M. Renjith,NaN,6.6,471.0
19991,1463030,Beyond Limits,10.000,3.0,2025-03-07,145000.0,93.0,62000.0,en,1.0161,...,STR,United Kingdom,"Mike Dunne, Joyce Jeffery, Hannah Marshall, Sa...",Raymond Mouzon,NaN,Raymond Mouzon,NaN,NaN,9.1,87.0
19993,1471503,Ashi Hi Jamva Jamvi,2.000,1.0,2025-04-10,141739.0,129.0,234280.0,mr,0.1786,...,NaN,India,"Omkar Kulkarni, Tanishka Vishe, Vandana Gupte,...",Lokesh Vijay Gupte,NaN,"Vibhav Rajadhyaksha, Kshitij Patwardhan, Lokes...","Rahul Shantaram, Omkar Hardikar",NaN,8.6,20.0
19994,1472280,Winter Dawn,0.000,0.0,2007-04-22,12500.0,15.0,2400.0,pt,0.0357,...,Moinho dell' Arte,Brazil,"Anselmo Vasconcelos, Maria Angélica Urbano",Carlos Alberto Sozza,NaN,Lúcio Lobo,NaN,NaN,8.0,7.0

In [ ]:
tmdb_df.reset_index(drop=True, inplace=True)

In [ ]:
tmdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12020 entries, 0 to 12019
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       12020 non-null  int64
 1   title                    12020 non-null  object
 2   vote_average             12020 non-null  float64
 3   vote_count               12020 non-null  float64
 4   release_date             12020 non-null  object
 5   revenue                  12020 non-null  float64
 6   runtime                  12020 non-null  float64
 7   budget                   12020 non-null  float64
 8   original_language        12020 non-null  object
 9   popularity               12020 non-null  float64
 10  genres                   12020 non-null  object
 11  production_companies     11618 non-null  object
 12  production_countries     11769 non-null  object
 13  cast                     11970 non-null  object
 14  director                 11970 non-null  object
 15  director_of_photography  10299 non-null  object
 16  writers                  11713 non-null  object
 17  producers                11108 non-null  object
 18  music_composer           9087 non-null   object
 19  imdb_rating              12020 non-null  float64
 20  imdb_votes               12020 non-null  float64
dtypes: float64(8), int64(1), object(12)
memory usage: 1.9+ MB

In [ ]:
print(tmdb_df.isna().sum())

id                            0
title                         0
vote_average                  0
vote_count                    0
release_date                  0
revenue                       0
runtime                       0
budget                        0
original_language             0
popularity                    0
genres                        0
production_companies        402
production_countries        251
cast                         50
director                     50
director_of_photography    1721
writers                     307
producers                   912
music_composer             2933
imdb_rating                   0
imdb_votes                    0
dtype: int64

In [ ]:
tmdb_df['profit_percentage'] = (((tmdb_df['revenue'] - tmdb_df['budget']) / tmdb_df['budget']) * 100)

In [ ]:
tmdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12020 entries, 0 to 12019
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       12020 non-null  int64
 1   title                    12020 non-null  object
 2   vote_average             12020 non-null  float64
 3   vote_count               12020 non-null  float64
 4   release_date             12020 non-null  object
 5   revenue                  12020 non-null  float64
 6   runtime                  12020 non-null  float64
 7   budget                   12020 non-null  float64
 8   original_language        12020 non-null  object
 9   popularity               12020 non-null  float64
 10  genres                   12020 non-null  object
 11  production_companies     11618 non-null  object
 12  production_countries     11769 non-null  object
 13  cast                     11970 non-null  object
 14  director                 11970 non-null  object
 15  director_of_photography  10299 non-null  object
 16  writers                  11713 non-null  object
 17  producers                11108 non-null  object
 18  music_composer           9087 non-null   object
 19  imdb_rating              12020 non-null  float64
 20  imdb_votes               12020 non-null  float64
 21  profit_percentage        12020 non-null  float64
dtypes: float64(9), int64(1), object(12)
memory usage: 2.0+ MB

In [ ]:
print(tmdb_df.isna().sum())

id                            0
title                         0
vote_average                  0
vote_count                    0
release_date                  0
revenue                       0
runtime                       0
budget                        0
original_language             0
popularity                    0
genres                        0
production_companies        402
production_countries        251
cast                         50
director                     50
director_of_photography    1721
writers                     307
producers                   912
music_composer             2933
imdb_rating                   0
imdb_votes                    0
profit_percentage             0
dtype: int64

In [ ]:
tmdb_df

,id,title,vote_average,vote_count,release_date,revenue,runtime,budget,original_language,popularity,...,production_countries,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,profit_percentage
0,5,Four Rooms,5.861,2687.0,1995-12-09,4257354.0,98.0,4000000.0,en,9.6284,...,United States of America,"Quinn Hellerman, Lawrence Bender, Tim Roth, La...","Allison Anders, Robert Rodriguez, Alexandre Ro...","Phil Parmet, Rodrigo García, Guillermo Navarro...","Allison Anders, Robert Rodriguez, Alexandre Ro...","Lawrence Bender, Alexandre Rockwell, Quentin T...",Combustible Edison,6.7,114082.0,6.433850e+00
1,6,Judgment Night,6.500,349.0,1993-10-15,12136938.0,109.0,21000000.0,en,4.5607,...,United States of America,"Michael Scranton, Hank McGill, Donovan D. Ross...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Lloyd Segan, Marilyn Vance",Alan Silvestri,6.6,19885.0,-4.220506e+01
2,11,Star Wars,8.204,21103.0,1977-05-25,775398007.0,121.0,11000000.0,en,67.2931,...,United States of America,"Paul Blake, Hal Wamsley, David Prowse, Larry W...",George Lucas,Gilbert Taylor,George Lucas,"Gary Kurtz, George Lucas, Rick McCallum",John Williams,8.6,1504993.0,6.949073e+03
3,12,Finding Nemo,7.815,19616.0,2003-05-30,940335536.0,100.0,94000000.0,en,18.2106,...,United States of America,"Jeff Pidgeon, Danny Mann, Jessie Flower, Bill ...",Andrew Stanton,"Sharon Calahan, Jeremy Lasky","Bob Peterson, Will Csaklos, Ronnie del Carmen,...","John Lasseter, Graham Walters",Thomas Newman,8.2,1158248.0,9.003570e+02
4,13,Forrest Gump,8.468,28113.0,1994-06-23,677387716.0,142.0,55000000.0,en,27.4853,...,United States of America,"Margo Moorer, Joe Stefanelli, Ed Davis, Elizab...",Robert Zemeckis,Don Burgess,"Winston Groom, Eric Roth","Wendy Finerman, Steve Tisch, Steve Starkey",Alan Silvestri,8.8,2374308.0,1.131614e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12015,1452426,24: Redemption,9.000,1.0,2008-11-23,13593473.0,102.0,4.0,en,0.8000,...,United States of America,"Colm Feore, Cherry Jones, Kiefer Sutherland, P...",Jon Cassar,NaN,"Robert Cochran, Joel Surnow, Howard Gordon",NaN,NaN,7.4,29411.0,3.398367e+08
12016,1457688,Love Under Construction,0.000,0.0,2025-02-28,600.0,186.0,600.0,ml,0.3335,...,India,"Ganga Meera, Gouri G Kishan, Neeraj Madhav, Aj...",Vishnu G Raghav,NaN,NaN,M. Renjith,NaN,6.6,471.0,0.000000e+00
12017,1463030,Beyond Limits,10.000,3.0,2025-03-07,145000.0,93.0,62000.0,en,1.0161,...,United Kingdom,"Mike Dunne, Joyce Jeffery, Hannah Marshall, Sa...",Raymond Mouzon,NaN,Raymond Mouzon,NaN,NaN,9.1,87.0,1.338710e+02
12018,1471503,Ashi Hi Jamva Jamvi,2.000,1.0,2025-04-10,141739.0,129.0,234280.0,mr,0.1786,...,India,"Omkar Kulkarni, Tanishka Vishe, Vandana Gupte,...",Lokesh Vijay Gupte,NaN,"Vibhav Rajadhyaksha, Kshitij Patwardhan, Lokes...","Rahul Shantaram, Omkar Hardikar",NaN,8.6,20.0,-3.950017e+01
12019,1472280,Winter Dawn,0.000,0.0,2007-04-22,12500.0,15.0,2400.0,pt,0.0357,...,Brazil,"Anselmo Vasconcelos, Maria Angélica Urbano",Carlos Alberto Sozza,NaN,Lúcio Lobo,NaN,NaN,8.0,7.0,4.208333e+02

In [ ]:
tmdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12020 entries, 0 to 12019
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       12020 non-null  int64
 1   title                    12020 non-null  object
 2   vote_average             12020 non-null  float64
 3   vote_count               12020 non-null  float64
 4   release_date             12020 non-null  object
 5   revenue                  12020 non-null  float64
 6   runtime                  12020 non-null  float64
 7   budget                   12020 non-null  float64
 8   original_language        12020 non-null  object
 9   popularity               12020 non-null  float64
 10  genres                   12020 non-null  object
 11  production_companies     11618 non-null  object
 12  production_countries     11769 non-null  object
 13  cast                     11970 non-null  object
 14  director                 11970 non-null  object
 15  director_of_photography  10299 non-null  object
 16  writers                  11713 non-null  object
 17  producers                11108 non-null  object
 18  music_composer           9087 non-null   object
 19  imdb_rating              12020 non-null  float64
 20  imdb_votes               12020 non-null  float64
 21  profit_percentage        12020 non-null  float64
dtypes: float64(9), int64(1), object(12)
memory usage: 2.0+ MB

In [ ]:
tmdb_df.to_csv('tmdb_profit.csv', index=False)